\default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: code_reading_gems_development

test:
  <<: *default
  database: code_reading_gems_test

production:
  <<: *default
  database: code_reading_gems_production
